package com.archmage.dinosaurus.components.cardsearch

// hard-coded for now, maybe revisit this when a new set comes out
// endpoint: /api/2.0/public/packs
object Pack {
  val values: Map[String, String] = Map(
    "core" -> "Core Set",
    "wla" -> "What Lies Ahead",
    "ta" -> "Trace Amount",
    "ce" -> "Cyber Exodus",
    "asis" -> "A Study in Static",
    "hs" -> "Humanity's Shadow",
    "fp" -> "Future Proof",
    "cac" -> "Creation and Control",
    "om" -> "Opening Moves",
    "st" -> "Second Thoughts",
    "mt" -> "Mala Tempora",
    "tc" -> "True Colors",
    "dt" -> "Double Time",
    "fal" -> "Fear and Loathing",
    "draft" -> "Draft",
    "hap" -> "Honor and Profit",
    "up" -> "Upstalk",
    "tsb" -> "The Spaces Between",
    "fc" -> "First Contact",
    "uao" -> "Up and Over",
    "atr" -> "All That Remains",
    "ts" -> "The Source",
    "oac" -> "Order and Chaos",
    "val" -> "The Valley",
    "bb" -> "Breaker Bay",
    "cc" -> "Chrome City",
    "uw" -> "The Underway",
    "oh" -> "Old Hollywood",
    "uot" -> "The Universe of Tomorrow",
    "dad" -> "Data and Destiny",
    "kg" -> "Kala Ghoda",
    "bf" -> "Business First",
    "dag" -> "Democracy and Dogma",
    "si" -> "Salsette Island",
    "tlm" -> "The Liberated Mind",
    "ftm" -> "Fear the Masses",
    "23s" -> "23 Seconds",
    "bm" -> "Blood Money",
    "es" -> "Escalation",
    "in" -> "Intervention",
    "ml" -> "Martial Law",
    "qu" -> "Quorum",
    "dc" -> "Daedalus Complex",
    "so" -> "Station One",
    "eas" -> "Earth's Scion",
    "td" -> "Terminal Directive",
    "baw" -> "Blood and Water",
    "fm" -> "Free Mars",
    "cd" -> "Crimson Dust",
    "core2" -> "Revised Core Set",
    "ss" -> "Sovereign Sight",
    "dtwn" -> "Down the White Nile",
    "cotc" -> "Council of the Crest",
    "tdatd" -> "The Devil and the Dragon",
    "win" -> "Whispers in Nalubaale",
    "ka" -> "Kampala Ascendent",
    "rar" -> "Reign and Reverie",
    "mo" -> "Magnum Opus",
    "napd" -> "NAPD Multiplayer"
  )
}
